'use client'
import './globals.css'
import 'bootstrap-icons/font/bootstrap-icons.css'
import { Inter, Montserrat, Roboto } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({
	subsets: ['latin'],
	weight: ['100', '300', '400', '500', '700', '900'],
})

export const metadata = {
	title: 'Simple Chat',
	description: 'Generated by create next app',
}

import { SessionProvider, signOut, useSession } from 'next-auth/react'
import { Header } from '../components/Header'
import useTheme from '../hooks/useTheme'
export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	const [theme, setTheme] = useTheme()
	return (
		<html lang='en'>
			<body
				className={`${inter.className} bg-white dark:bg-zinc-950  text-zinc-800 h-screen  w-full flex flex-col dark:text-zinc-200`}>
				<SessionProvider>
					<Header />
					{children}
				</SessionProvider>
			</body>
		</html>
	)
}
